---
title: "UK SIC Code Description Network Graph"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---


```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

```


```{r load_packages}

library(tidyverse)
library(tidytext)
library(widyr)
library(igraph)
library(networkD3)

```


```{r import_data}

# download the csv from 
# https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/527619/SIC07_CH_condensed_list_en.csv

sic_descr_df <- read_csv('SIC07_CH_condensed_list_en.csv')

```


```{r description_cosine_similarity}


term_freq_df <-
  sic_descr_df %>%
  unnest_tokens(output = word,
                input = Description,
                drop = FALSE) %>%
  # anti_join(stop_words) %>%
  count(`SIC Code`,
        Description,
        word)



cos_sim_df <-
  term_freq_df %>%
  pairwise_similarity(Description,
                      word,
                      n)

```


```{r term_frequency_review}

top_terms <-
  term_freq_df %>%
  anti_join(stop_words) %>%
  group_by(word) %>%
  summarise(n = sum(n)) %>%
  arrange(desc(n),
          word) %>%
  head(50)

```


```{r similarity_distribution}


qtl_cutoff <-
  quantile(cos_sim_df %>%
             filter(similarity > 0.5) %>%
             pull(similarity))[4]



cs_hist <-
  cos_sim_df %>%
  ggplot(aes(x = similarity)) +
  geom_histogram() +
  geom_vline(xintercept = qtl_cutoff[1],
             linetype = 2) +
  geom_text(aes(
    x = qtl_cutoff[1],
    y = Inf,
    label = round(qtl_cutoff[1], 3),
    vjust = 'inward'
  ))


```



### Graph

```{r network_graph}


cs_filter <- 0.69



sic_graph <-
  cos_sim_df %>%
  # filter(similarity >= qtl_cutoff[1]) %>%
  # filter(str_detect(str_to_lower(item1), 'manufacture')) %>%
  filter(similarity > cs_filter) %>%
  select(item1, item2) %>%
  graph_from_data_frame(directed = FALSE)


sic_wc <- cluster_walktrap(sic_graph)

sic_members <- membership(sic_wc)


sic_membership_df <-
  tibble(membership = sic_wc$membership,
         names = sic_wc$names)




sic_membership_filter <-
  sic_membership_df %>%
  group_by(membership) %>%
  mutate(n = n()) %>%
  ungroup() %>%
  filter(n > 2) %>% 
  pull(names)







sic_graph_filtered <-
  cos_sim_df %>%
  filter(similarity > cs_filter) %>%
  filter(item1 %in% sic_membership_filter) %>%
  select(item1, item2) %>%
  graph_from_data_frame(directed = FALSE)


sic_wc_filtered <- cluster_walktrap(sic_graph_filtered)

sic_members_filtered <- membership(sic_wc_filtered)




sic_d3 <- igraph_to_networkD3(sic_graph_filtered,
                              group = sic_members_filtered)



forceNetwork(
  Links = sic_d3$links,
  Nodes = sic_d3$nodes,
  Source = 'source',
  Target = 'target',
  NodeID = 'name',
  Group = 'group',
  charge = -40,
  opacity = 1,
  opacityNoHover = 1,
  height = 81 * 10,
  width = 81 * 19,
  fontSize = 5,
  bounded = FALSE,
  zoom = TRUE
)

```






